[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "light"

[runner]
magicEnabled = false
fastReruns = true

[client]
showSidebarNavigation = false

[global]
developmentMode = false